PUBLIC_DATA_PORTAL_KEY = '{{API 사용 신청 시 발급받은 service key}}'
PUBLIC_DATA_DOMAIN = 'http://apis.data.go.kr'

DEFAULT_NUM_PAGE = 100

PUBLIC_DATA_HOLIDAY_URI = 'B090041/openapi/service/SpcdeInfoService'
PUBLIC_DATA_HOLIDAY_HOLIDAY_OP = 'getHoliDeInfo'
PUBLIC_DATA_HOLIDAY_REST_OP = 'getRestDeInfo'
PUBLIC_DATA_HOLIDAY_ANNIVERSARY_OP = 'getAnniversaryInfo'
PUBLIC_DATA_HOLIDAY_DIVISIOM_OP = 'get24DivisionsInfo'
PUBLIC_DATA_HOLIDAY_SUNDRY_OP = 'getSundryDayInfo'
